# Generated by Django 4.0.1 on 2022-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('disciplina', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.DateField(blank=True)),
                ('ciudad_de_nacimiento', models.CharField(max_length=30)),
                ('pais_de_nacimiento', models.CharField(max_length=30)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.DateField(blank=True)),
                ('estudios', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField(blank=True)),
                ('intensidad', models.CharField(max_length=10)),
                ('ejercicio_1', models.CharField(max_length=40)),
                ('ejercicio_2', models.CharField(max_length=40)),
                ('ejercicio_3', models.CharField(max_length=40)),
                ('ejercicio_4', models.CharField(max_length=40)),
                ('ejercicio_5', models.CharField(max_length=40)),
                ('ejercicio_6', models.CharField(max_length=40)),
                ('ejercicio_7', models.CharField(max_length=40)),
                ('duracionPorEjercicio', models.IntegerField()),
                ('descansoEntreEjercicio', models.IntegerField()),
                ('rondas', models.IntegerField()),
            ],
        ),
    ]
