# Generated by Django 4.0.1 on 2022-02-11 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
